### ISSUE TITLE
Issues with IPv6 on latest version of container

### ISSUE THREAD

**Issue by Sn0wCrack** [qdm12/private-internet-access-docker#86]
**System Information**:
 - Host OS: Ubuntu 19.10
 - Docker Version: 19.03.3
 - Docker Compose: 1.12.0

With the latest release of the Container I've switched over to Mullvard and the container appears to be having issues starting up OpenVPN and is failing when attempting to add an IPv6 address to the tunnel device.

Here's a snippet from my container's log file:
```
2020-03-03T10:21:21.995+1100    INFO    openvpn configurator: starting openvpn
2020-03-03T10:21:21.997+1100    INFO    openvpn: Tue Mar  3 10:21:21 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
2020-03-03T10:21:21.998+1100    INFO    openvpn: Tue Mar  3 10:21:21 2020 OpenVPN 2.4.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb  7 2020
2020-03-03T10:21:21.998+1100    INFO    openvpn: Tue Mar  3 10:21:21 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
2020-03-03T10:21:22.002+1100    INFO    openvpn: Tue Mar  3 10:21:22 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]116.206.228.242:1300
2020-03-03T10:21:22.002+1100    INFO    openvpn: Tue Mar  3 10:21:22 2020 UDP link local: (not bound)
2020-03-03T10:21:22.002+1100    INFO    openvpn: Tue Mar  3 10:21:22 2020 UDP link remote: [AF_INET]116.206.228.242:1300
2020-03-03T10:21:22.002+1100    INFO    openvpn: Tue Mar  3 10:21:22 2020 NOTE: UID/GID downgrade will be delayed because of --client, --pull, or --up-delay
2020-03-03T10:21:22.246+1100    INFO    openvpn: Tue Mar  3 10:21:22 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558'
2020-03-03T10:21:22.246+1100    INFO    openvpn: Tue Mar  3 10:21:22 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2020-03-03T10:21:22.246+1100    INFO    openvpn: Tue Mar  3 10:21:22 2020 [au-mel-003.mullvad.net] Peer Connection Initiated with [AF_INET]116.206.228.242:1300
2020-03-03T10:21:28.400+1100    INFO    openvpn: Tue Mar  3 10:21:28 2020 NOTE: setsockopt TCP_NODELAY=1 failed
2020-03-03T10:21:28.402+1100    INFO    openvpn: Tue Mar  3 10:21:28 2020 TUN/TAP device tun0 opened
2020-03-03T10:21:28.402+1100    INFO    openvpn: Tue Mar  3 10:21:28 2020 /sbin/ip link set dev tun0 up mtu 1500
2020-03-03T10:21:28.404+1100    INFO    openvpn: Tue Mar  3 10:21:28 2020 /sbin/ip addr add dev tun0 10.14.0.2/16 broadcast 10.14.255.255
2020-03-03T10:21:28.406+1100    INFO    openvpn: Tue Mar  3 10:21:28 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1300::1000/64 dev tun0
2020-03-03T10:21:28.408+1100    INFO    openvpn: Tue Mar  3 10:21:28 2020 Linux ip -6 addr add failed: external program exited with error status: 2
2020-03-03T10:21:28.409+1100    INFO    openvpn: Tue Mar  3 10:21:28 2020 Exiting due to fatal error
2020-03-03T10:21:28.437+1100    ERROR   exit status 1
```

I'm not 100% sure if this has anything to do with my host system setup, but IPv6 is enabled within the OS, and it can be used on my local network successfully.

**Comment by qdm12** [comment]
That is indeed related to ipv6 and `ip -6 add ...` not working.

It's unlikely this, but, just in case, do you mind running on your host:

```sh
cat /proc/sys/net/ipv6/conf/all/disable_ipv6
```

If the output is `1` then run `echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6` and try again? If not, I'm still digging 😄

**Comment by Sn0wCrack** [comment]
@qdm12 

Thanks for looking into it, I actually did a bit of searching myself before submitting, and yeah that's already returning 0 at the moment.

**Comment by qdm12** [comment]
Ok for the time being, I'll just disable openvpn tunneling ipv6, would that be ok in your situation? Was it working without ipv6 before?

**Comment by Sn0wCrack** [comment]
Yeah I was previously using the container with PIA just fine.
With the recent update I wanted to switch over to Mullvad and this error started occurring, I haven't tried PIA on this version of the container properly yet however.

**Comment by qdm12** [comment]
Ok I just pushed [this commit](https://github.com/qdm12/private-internet-access-docker/commit/d707adb9b7d5cd8d3c7a0b9352fcacdd26aeb473) commenting out the ipv6 part I added.

You can pull the Docker image once [the Travis build is finished](https://travis-ci.org/qdm12/private-internet-access-docker/builds/657544487) 😉  Let's leave this issue open so I can tackle it some day.

**Comment by Sn0wCrack** [comment]
I updated my Docker image to the latest version however the issue still persisted.

I ended up fixing the issue by adding the following the service within my docker compose file:

```
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
```

**Comment by qdm12** [comment]
Do you mind trying again without that `sysctls`? What's the version shown at the top of the logs of the container running? As I disabled the ipv6 tunneling, it seems strange it's still failing. Thanks!

**Comment by ljmerza** [comment]
I get the same issue and it's fixed with the same line @Sn0wCrack  mentioned. I also get an error every few minutes though not sure if related


```
openvpn2          | 2020-03-03T20:05:36.115-0500        INFO    openvpn: Tue Mar  3 20:05:36 2020 [se-sto-006.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:05:42.859-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:05:42.861-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 TUN/TAP device tun0 opened
openvpn2          | 2020-03-03T20:05:42.861-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 /sbin/ip link set dev tun0 up mtu 1500
openvpn2          | 2020-03-03T20:05:42.866-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 /sbin/ip addr add dev tun0 10.16.0.6/16 broadcast 10.16.255.255
openvpn2          | 2020-03-03T20:05:42.868-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1302::1004/64 dev tun0
openvpn2          | 2020-03-03T20:05:42.874-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 add_route_ipv6(::/2 -> fdda:d0d0:cafe:1302:: metric -1) dev tun0
openvpn2          | 2020-03-03T20:05:42.876-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 add_route_ipv6(4000::/2 -> fdda:d0d0:cafe:1302:: metric -1) dev tun0
openvpn2          | 2020-03-03T20:05:42.878-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 add_route_ipv6(8000::/2 -> fdda:d0d0:cafe:1302:: metric -1) dev tun0
openvpn2          | 2020-03-03T20:05:42.879-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 add_route_ipv6(c000::/2 -> fdda:d0d0:cafe:1302:: metric -1) dev tun0
openvpn2          | 2020-03-03T20:05:42.881-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 UID set to nonrootuser
openvpn2          | 2020-03-03T20:05:42.881-0500        INFO    openvpn: Tue Mar  3 20:05:42 2020 Initialization Sequence Completed
openvpn2          | 2020-03-03T20:10:18.160-0500        INFO    openvpn: Tue Mar  3 20:10:18 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:10:20.112-0500        INFO    openvpn: Tue Mar  3 20:10:20 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:10:22.080-0500        INFO    openvpn: Tue Mar  3 20:10:22 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:10:49.360-0500        INFO    openvpn: Tue Mar  3 20:10:49 2020 [se-sto-006.mullvad.net] Inactivity timeout (--ping-restart), restarting
openvpn2          | 2020-03-03T20:10:49.360-0500        INFO    openvpn: Tue Mar  3 20:10:49 2020 SIGUSR1[soft,ping-restart] received, process restarting
openvpn2          | 2020-03-03T20:10:59.361-0500        INFO    openvpn: Tue Mar  3 20:10:59 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:10:59.361-0500        INFO    openvpn: Tue Mar  3 20:10:59 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:10:59.361-0500        INFO    openvpn: Tue Mar  3 20:10:59 2020 UDP link local: (not bound)
openvpn2          | 2020-03-03T20:10:59.361-0500        INFO    openvpn: Tue Mar  3 20:10:59 2020 UDP link remote: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:11:00.345-0500        INFO    openvpn: Tue Mar  3 20:11:00 2020 [se-sto-006.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:11:06.845-0500        INFO    openvpn: Tue Mar  3 20:11:06 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:11:06.845-0500        INFO    openvpn: Tue Mar  3 20:11:06 2020 Preserving previous TUN/TAP instance: tun0
openvpn2          | 2020-03-03T20:11:06.845-0500        INFO    openvpn: Tue Mar  3 20:11:06 2020 Initialization Sequence Completed
openvpn2          | 2020-03-03T20:13:52.368-0500        INFO    openvpn: Tue Mar  3 20:13:52 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:13:55.196-0500        INFO    openvpn: Tue Mar  3 20:13:55 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:13:55.196-0500        INFO    openvpn: Tue Mar  3 20:13:55 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:13:58.409-0500        INFO    openvpn: Tue Mar  3 20:13:58 2020 [se-sto-006.mullvad.net] Inactivity timeout (--ping-restart), restarting
openvpn2          | 2020-03-03T20:13:58.410-0500        INFO    openvpn: Tue Mar  3 20:13:58 2020 SIGUSR1[soft,ping-restart] received, process restarting
openvpn2          | 2020-03-03T20:14:08.411-0500        INFO    openvpn: Tue Mar  3 20:14:08 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:14:08.412-0500        INFO    openvpn: Tue Mar  3 20:14:08 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:14:08.412-0500        INFO    openvpn: Tue Mar  3 20:14:08 2020 UDP link local: (not bound)
openvpn2          | 2020-03-03T20:14:08.412-0500        INFO    openvpn: Tue Mar  3 20:14:08 2020 UDP link remote: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:14:09.282-0500        INFO    openvpn: Tue Mar  3 20:14:09 2020 [se-sto-006.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:14:15.728-0500        INFO    openvpn: Tue Mar  3 20:14:15 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:14:15.728-0500        INFO    openvpn: Tue Mar  3 20:14:15 2020 Preserving previous TUN/TAP instance: tun0
openvpn2          | 2020-03-03T20:14:15.728-0500        INFO    openvpn: Tue Mar  3 20:14:15 2020 Initialization Sequence Completed
openvpn2          | 2020-03-03T20:17:28.797-0500        INFO    openvpn: Tue Mar  3 20:17:28 2020 [se-sto-006.mullvad.net] Inactivity timeout (--ping-restart), restarting
openvpn2          | 2020-03-03T20:17:28.798-0500        INFO    openvpn: Tue Mar  3 20:17:28 2020 SIGUSR1[soft,ping-restart] received, process restarting
openvpn2          | 2020-03-03T20:17:38.799-0500        INFO    openvpn: Tue Mar  3 20:17:38 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:17:38.799-0500        INFO    openvpn: Tue Mar  3 20:17:38 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:17:38.799-0500        INFO    openvpn: Tue Mar  3 20:17:38 2020 UDP link local: (not bound)
openvpn2          | 2020-03-03T20:17:38.799-0500        INFO    openvpn: Tue Mar  3 20:17:38 2020 UDP link remote: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:17:39.560-0500        INFO    openvpn: Tue Mar  3 20:17:39 2020 [se-sto-006.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:17:40.864-0500        INFO    openvpn: Tue Mar  3 20:17:40 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:17:40.864-0500        INFO    openvpn: Tue Mar  3 20:17:40 2020 Preserving previous TUN/TAP instance: tun0
openvpn2          | 2020-03-03T20:17:40.864-0500        INFO    openvpn: Tue Mar  3 20:17:40 2020 Initialization Sequence Completed
openvpn2          | 2020-03-03T20:19:58.552-0500        INFO    openvpn: Tue Mar  3 20:19:58 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:20:01.080-0500        INFO    openvpn: Tue Mar  3 20:20:01 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:20:01.080-0500        INFO    openvpn: Tue Mar  3 20:20:01 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:20:15.068-0500        INFO    openvpn: Tue Mar  3 20:20:15 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:20:17.272-0500        INFO    openvpn: Tue Mar  3 20:20:17 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:20:18.071-0500        INFO    openvpn: Tue Mar  3 20:20:18 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:20:35.305-0500        INFO    openvpn: Tue Mar  3 20:20:35 2020 [se-sto-006.mullvad.net] Inactivity timeout (--ping-restart), restarting
openvpn2          | 2020-03-03T20:20:35.306-0500        INFO    openvpn: Tue Mar  3 20:20:35 2020 SIGUSR1[soft,ping-restart] received, process restarting
openvpn2          | 2020-03-03T20:20:45.307-0500        INFO    openvpn: Tue Mar  3 20:20:45 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:20:45.307-0500        INFO    openvpn: Tue Mar  3 20:20:45 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:20:45.308-0500        INFO    openvpn: Tue Mar  3 20:20:45 2020 UDP link local: (not bound)
openvpn2          | 2020-03-03T20:20:45.308-0500        INFO    openvpn: Tue Mar  3 20:20:45 2020 UDP link remote: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:20:46.220-0500        INFO    openvpn: Tue Mar  3 20:20:46 2020 [se-sto-006.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:20:47.560-0500        INFO    openvpn: Tue Mar  3 20:20:47 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:20:47.560-0500        INFO    openvpn: Tue Mar  3 20:20:47 2020 Preserving previous TUN/TAP instance: tun0
openvpn2          | 2020-03-03T20:20:47.560-0500        INFO    openvpn: Tue Mar  3 20:20:47 2020 Initialization Sequence Completed
openvpn2          | 2020-03-03T20:23:02.102-0500        INFO    openvpn: Tue Mar  3 20:23:02 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:03.658-0500        INFO    openvpn: Tue Mar  3 20:23:03 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:04.573-0500        INFO    openvpn: Tue Mar  3 20:23:04 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:05.186-0500        INFO    openvpn: Tue Mar  3 20:23:05 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:06.443-0500        INFO    openvpn: Tue Mar  3 20:23:06 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:07.463-0500        INFO    openvpn: Tue Mar  3 20:23:07 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:09.111-0500        INFO    openvpn: Tue Mar  3 20:23:09 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:09.111-0500        INFO    openvpn: Tue Mar  3 20:23:09 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:14.098-0500        INFO    openvpn: Tue Mar  3 20:23:14 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:16.068-0500        INFO    openvpn: Tue Mar  3 20:23:16 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:18.108-0500        INFO    openvpn: Tue Mar  3 20:23:18 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:18.108-0500        INFO    openvpn: Tue Mar  3 20:23:18 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:30.283-0500        INFO    openvpn: Tue Mar  3 20:23:30 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:32.412-0500        INFO    openvpn: Tue Mar  3 20:23:32 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:34.709-0500        INFO    openvpn: Tue Mar  3 20:23:34 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:36.219-0500        INFO    openvpn: Tue Mar  3 20:23:36 2020 TLS Error: Unroutable control packet received from [AF_INET]185.65.135.136:1302 (si=3 op=P_CONTROL_V1)
openvpn2          | 2020-03-03T20:23:38.393-0500        INFO    openvpn: Tue Mar  3 20:23:38 2020 [se-sto-006.mullvad.net] Inactivity timeout (--ping-restart), restarting
openvpn2          | 2020-03-03T20:23:38.394-0500        INFO    openvpn: Tue Mar  3 20:23:38 2020 SIGUSR1[soft,ping-restart] received, process restarting
openvpn2          | 2020-03-03T20:23:48.395-0500        INFO    openvpn: Tue Mar  3 20:23:48 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:23:48.395-0500        INFO    openvpn: Tue Mar  3 20:23:48 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:23:48.395-0500        INFO    openvpn: Tue Mar  3 20:23:48 2020 UDP link local: (not bound)
openvpn2          | 2020-03-03T20:23:48.395-0500        INFO    openvpn: Tue Mar  3 20:23:48 2020 UDP link remote: [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:23:49.285-0500        INFO    openvpn: Tue Mar  3 20:23:49 2020 [se-sto-006.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.135.136:1302
openvpn2          | 2020-03-03T20:23:50.504-0500        INFO    openvpn: Tue Mar  3 20:23:50 2020 NOTE: setsockopt TCP_NODELAY=1 failed
openvpn2          | 2020-03-03T20:23:50.504-0500        INFO    openvpn: Tue Mar  3 20:23:50 2020 Preserving previous TUN/TAP instance: tun0
openvpn2          | 2020-03-03T20:23:50.504-0500        INFO    openvpn: Tue Mar  3 20:23:50 2020 Initialization Sequence Completed
```

**Comment by qdm12** [comment]
@ljmerza Thanks for reporting, on PIA or Mullvad ?

**Comment by Sn0wCrack** [comment]
@qdm12 

I remove the sysctl, pulled, stopped and started my containers again (down, then up -d rather than restart) and the issue still appears to persist, adding it back in again fixes the issue.

These are the versions from the top of my log file:

```
Running version latest built on 2020-03-03T00:24:44Z (commit d707adb)

2020-03-04T12:37:58.828+1100    INFO    OpenVPN version: 2.4.8
2020-03-04T12:37:58.831+1100    INFO    Unbound version: 1.9.6
2020-03-04T12:37:58.833+1100    INFO    IPtables version: v1.8.3
2020-03-04T12:37:58.868+1100    INFO    TinyProxy version: 1.10.0
2020-03-04T12:37:58.871+1100    INFO    ShadowSocks version: 3.3.4
```

The commit hash seems to line up with your commit for removing the tun-ipv6 parameter.

Something to note might be a message that appeared in my logs with the prior version of the container:

```
Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
```

Also just to note I'm not having the issue that @ljmerza  is having, after adding that line to my docker compose file, however I do seem to get kicked from Mullvad every now and then for inactivity on the VPN connection, however it hasn't happened since yesterday

**Comment by ljmerza** [comment]
@qdm12 mullvad

**Comment by qdm12** [comment]
Ok I'll look into it tomorrow, sorry for the bug.

Maybe Mullvad pushes the tun-ipv6 from their server so even if it's commented it's still enabled for the connection.

There may be a way to build the ipv6 fix inside the Docker image.

@Sn0wCrack I'll also add a regular ping in the openvpn configuration so it doesn't time out (if it's not there already)

@ljmerza I'll check the error you get, but it might be because of some packet sizes I tried to not set using Mullvad settings (they're commented out) I'll uncomment them to see if it fixes your problem.

Thanks guys for reporting and the debugging!

**Comment by ljmerza** [comment]
@qdm12 One more thing I noticed, half my torrents can't connect to their trackers anymore. I don't see anything in my logs about it. I'm thinking maybe a DNS issue. I haven't set anything for that though. Been using this through PIA just fine for months.

**Comment by Sn0wCrack** [comment]
I have also noticed in my logs that every few DNS requests tend to fail when I have DOT turned on, turning it off I no longer see those errors.

I don't see it as much of an issue as the DNS request usually retries right aware and works fine.

**Comment by qdm12** [comment]
Turning off will use whatever DNS provided by Mullvad's ISP, so errors won't show in the logs and may still happen, although not with Unbound.

What's your DOT verbosity settings? Do you mind attaching a log file of the DOT errors logged? Maybe post it in #88

**Comment by qdm12** [comment]
So I did multiple modifications regarding this issue, see the other issue #88 for the hostname resolution and IPv6.

- I aligned with Mullvad ping settings, so it should not disconnect on a timeout anymore
- I think for ipv6 the only way is to set in your docker run command as you did, so I added documentation in the readme for it. Looks like a Docker issue sadly. And it is likely Mullvad pushes settings to the clients to tunnel ipv6, hence you need that for Mullvad if you have IPv6 enabled on your host.

Let me know if it works out for you.
